### ISSUE TITLE
cannot use comment mode 

### ISSUE THREAD

**Issue by 261209** [meet447/Reddit-Karma-Bot#4]
SUCCESS] - recived title
SUCCESS] - recived content
Traceback (most recent call last):
  File "C:\Users\Le\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Le\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Le\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Le\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Le\Reddit-Karma-Bot\llm\main.py", line 20, in create_response
    response_data = response.json()
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Le\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Le\Reddit-Karma-Bot\app.py", line 236, in <module>
    reddit_bot.run()
  File "C:\Users\Le\Reddit-Karma-Bot\app.py", line 229, in run
    self.generate_comment(
  File "C:\Users\Le\Reddit-Karma-Bot\app.py", line 114, in generate_comment
    comment = create_response(post=new_prompt)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Le\Reddit-Karma-Bot\llm\main.py", line 57, in create_response
    g4f.Provider.Vercel,
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'g4f.Provider' has no attribute 'Vercel'

**Comment by sammadox** [comment]
Hello, have you tried to check the response object?

**Comment by meet447** [comment]
i will look into it

**Comment by chenlyuzhao** [comment]
@sammadox / @meet447 
Hello, can I get some help on this please.
I am getting the same error, I added print(response) in llm/main,py

[PROCESSING POST] - 'He slapped the heII out of him lmao'
[PROXY] - All proxies failed. Trying without proxy.
[LOGIN] - Attempting login for nelsonfgn9z
[LOGIN] - Logged in as nelsonfgn9z
<Response [402]>

Is it because the api_key in llm/main.py needs change?
Also, how would [PROXY] - All proxies failed. Trying without proxy affect the usage?

**Comment by chenlyuzhao** [comment]
Just see @meet447 has the repo: https://github.com/meet447/Chipling-AI
I guess we also need to setup that.

**Comment by meet447** [comment]
You don't need to setup that the 402 error is from g4f, g4f sometimes make 402 error i will update the code so that if 402 error it try to fetch response again

> Just see @meet447 has the repo: https://github.com/meet447/Chipling-AI I guess we also need to setup that.

**Comment by meet447** [comment]
@sammadox  i have updated the code 402 error should be fixed
